import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://betterdocs.msf.shahrear.site/');
  await page.locator('#menu-item-174').getByRole('link', { name: 'Category Box Menu Toggle' }).click();
  await page.getByRole('link', { name: 'All In All MSF 1 Doc' }).click();
  await page.getByPlaceholder('Search...').click();
  await page.getByPlaceholder('Search...').fill('mercedes');
  await page.getByRole('link', { name: 'Mercedes GLS450: Here’s why every driveway of upscale Dhaka has one All In All' }).click();
  await page.locator('#betterdocs-single-content').getByText('Updated on September 25,').click();
  await page.getByText('Updated on September 25,').nth(2).click();
  await page.locator('div').filter({ hasText: /^sunset507 KB$/ }).nth(1).click();
  await page.locator('#betterdocs-single-main').getByText('Related Docs').click();
  await page.getByRole('link', { name: 'Does your solution provide an' }).click();
  await page.getByRole('heading', { name: 'Was it helpful ?' }).click();
  await page.getByRole('heading', { name: 'Share This Article :' }).click();
  await page.getByRole('link', { name: 'Setup Process' }).click();
  await page.getByRole('combobox').selectOption('allinallmsf');
  await page.getByPlaceholder('Search...').click();
  await page.getByPlaceholder('Search...').fill('mercedes');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'Docs', exact: true }).click();
  await page.getByRole('link', { name: 'API & Development 4 docs Last' }).click();
  await page.getByRole('link', { name: 'Category Grid' }).click();
  await page.getByText('Updated on September 11,').click();
  await page.getByRole('heading', { name: 'API & Development' }).click();
  await page.getByText('4', { exact: true }).first().click();
  await page.locator('.betterdocs-category-items-counts').first().click();
  await page.locator('.betterdocs-category-header').first().click();
  await page.locator('#post-129 article').filter({ hasText: 'API & Development 4 Does your' }).getByRole('link').nth(4).click();
  await page.locator('#main').getByRole('link', { name: 'Can scale for growth and' }).click();
  await page.getByText('Search...').click();
  await page.getByPlaceholder('Search...').click();
  await page.getByText('ESC', { exact: true }).click();
  await page.locator('.css-19bb58m').click();
  await page.getByRole('option', { name: 'API &amp; Development' }).click();
  await page.locator('div').filter({ hasText: /^Docs$/ }).click();
  await page.locator('#betterdocs-search-modal').getByText('FAQ').click();
  await page.getByRole('heading', { name: 'Sunlight' }).click();
  await page.getByText('Certainly! Here is a sample').click();
  await page.getByText('Certainly! Here is a sample').click();
  await page.getByText('Certainly! Here is a sample').click();
  await page.locator('#betterdocs-search-modal').getByText('Docs').click();
  await page.getByRole('link', { name: 'Mercedes GLS450: Here’s why' }).click();
  await page.locator('#betterdocs-full-sidebar-left div').filter({ hasText: 'Mercedes GLS450: Here’s why' }).nth(4).click();
  await page.getByRole('link', { name: 'Popular Docs_Related' }).click();
  await page.getByRole('heading', { name: 'Popular Docs_Related' }).click();
  await page.getByText('Updated on June 30,').click();
  await page.getByRole('heading', { name: 'Popular Docs', exact: true }).click();
  await page.locator('li').filter({ hasText: 'Mercedes GLS450: Here’s why' }).getByRole('img').click();
  await page.getByRole('heading', { name: 'Related Categories', exact: true }).click();
  await page.getByRole('link', { name: 'All In All MSF' }).click();
  await page.locator('h2').click();
  await page.getByText('Here you will find the docs').click();
  await page.locator('#main').getByRole('link', { name: 'Mercedes GLS450: Here’s why' }).click();
  await page.getByRole('link', { name: 'Sidebar' }).click();
  await page.getByRole('heading', { name: 'API & Development' }).click();
  await page.getByRole('heading', { name: 'Architecture & Infastructure' }).click();
  await page.getByRole('heading', { name: 'Getting Started' }).click();
  await page.locator('#betterdocs-sidebar article').filter({ hasText: 'Getting Started 4 Ability to' }).locator('img').first().click();
  await page.getByRole('heading', { name: 'Getting Started' }).click();
  await page.getByRole('heading', { name: 'Setup Process' }).click();
  await page.getByRole('link', { name: 'Category Handbook' }).click();
  await page.getByRole('heading', { name: 'Category Handbook' }).click();
  await page.getByRole('heading', { name: 'All In All MSF' }).click();
  await page.locator('#post-144 article').filter({ hasText: 'All In All MSF 1 Here you' }).locator('img').click();
  await page.locator('#post-144 article').filter({ hasText: 'All In All MSF 1 Here you' }).getByRole('link').nth(1).click();
  await page.getByRole('link', { name: 'Multiple KB', exact: true }).click();
  await page.getByText('No posts found!').click();
  await page.getByRole('heading', { name: 'Multiple KB' }).click();
  await page.locator('#menu-item-174').getByRole('link', { name: 'Category Box Menu Toggle' }).click();
  await page.locator('#menu-item-174').getByRole('link', { name: 'Category Box Menu Toggle' }).click();
  await page.getByRole('link', { name: 'Multiple KB Tab' }).click();
  await page.getByRole('link', { name: 'MSF', exact: true }).click();
  await page.locator('#encyclopedia-container').getByRole('link').nth(2).click();
  await page.locator('#betterdocs-breadcrumb').getByText('победитель · призер').click();
  await page.getByRole('link', { name: 'MSF', exact: true }).click();
  await page.locator('#encyclopedia-container').getByRole('link').nth(2).click();
  await page.getByRole('link', { name: 'FAQ' }).click();
  await page.getByRole('heading', { name: 'Frequently Asked Questions' }).click();
  await page.getByRole('heading', { name: 'Shipping & Delivery' }).click();
  await page.locator('.betterdocs-faq-post').first().click();
  await page.getByText('We usually take 3-5 business').first().click();
  await page.locator('li:nth-child(4) > .betterdocs-faq-group > .betterdocs-faq-post').first().click();
  await page.locator('ul:nth-child(8) > li > .betterdocs-faq-group > .betterdocs-faq-post').first().click();
  await page.getByText('We accept all the popular').first().click();
  await page.getByText('We accept all the popular').first().click();
  await page.locator('ul:nth-child(8) > li:nth-child(4) > .betterdocs-faq-group > .betterdocs-faq-post').click();
  await page.getByText('You will receive an email').nth(1).click();
  await page.getByRole('link', { name: 'Single Docs' }).click();
  await page.locator('#menu-item-251').getByRole('link', { name: 'Category Box Menu Toggle' }).click();
  await page.getByRole('link', { name: 'Benefit, Reward, Voucher &' }).click();
  await page.getByText('API & Development 4').click();
  await page.locator('.betterdocs-category-header').first().click();
  await page.locator('article').filter({ hasText: 'API & Development 4 Can scale' }).locator('span').first().click();
  await page.locator('.betterdocs-category-items-counts').first().click();
  await page.getByRole('link', { name: 'Can your loyalty platform' }).first().click();
  await page.getByRole('heading', { name: 'Can your loyalty platform' }).click();
  await page.getByRole('heading', { name: 'Share This Article :' }).click();
  await page.locator('.simplebar-content > div').first().click();
  await page.locator('.layout-3').first().click();
  await page.getByRole('link', { name: 'Normal' }).click();
  await page.getByRole('link', { name: 'Category Archive List' }).click();
  await page.getByText('Updated on September 26,').click();
  await page.getByText('Home Docs').click();
  await page.locator('li').filter({ hasText: '70% of Bangladesh’s outward' }).click();
  await page.locator('div:nth-child(4) > .elementor-widget-container > .betterdocs-elementor').click();
  await page.getByRole('link', { name: 'Still stuck? How can we help?' }).click();
  await page.getByRole('heading', { name: 'How can we help?' }).click();
  await page.getByLabel('Name: *').click();
  await page.getByLabel('Name: *').fill('Shahrear');
  await page.getByLabel('Email: *').click();
  await page.getByLabel('Email: *').fill('ha@gmail.com');
  await page.getByLabel('Message: *').click();
  await page.getByLabel('Message: *').fill('Hi');
  await page.getByRole('heading', { name: 'How can we help?' }).click();
  await page.locator('#betterdocs-form-modal').getByRole('link').click();
  await page.getByRole('link', { name: 'Encyclopedia' }).click();
  await page.locator('#encyclopedia-container').getByRole('link').nth(2).click();
  await page.getByRole('link', { name: 'Multiple KB' }).click();
  await page.locator('.e-con-inner').click();
  await page.getByRole('link', { name: 'Popular Docs' }).click();
  await page.getByRole('link', { name: 'Mercedes GLS450: Here’s why' }).click();
  await page.getByRole('link', { name: 'Popular Docs' }).click();
  await page.getByRole('heading', { name: 'Popular Docs' }).click();
  await page.getByRole('link', { name: 'Mercedes GLS450: Here’s why' }).click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Sidebar' }).click();
  await page.getByText('API & Development 4').click();
  await page.locator('#betterdocs-sidebar article').filter({ hasText: 'API & Development 4 Can scale' }).locator('span').first().click();
  await page.locator('.betterdocs-category-header').first().click();
  await page.getByRole('link', { name: 'FAQ' }).click();
  await page.locator('.betterdocs-faq-post').first().click();
  await page.locator('li:nth-child(2) > .betterdocs-faq-group > .betterdocs-faq-post').first().click();
  await page.getByText('Yes, free shipping is').first().click();
  await page.getByRole('link', { name: 'Tab View List' }).click();
  await page.getByText('Whoops! It seems like you').click();
  await page.getByRole('link', { name: 'Category Box 2 SC Menu Toggle' }).click();
  await page.getByRole('heading', { name: 'Category Box 2 SC' }).click();
  await page.getByRole('link', { name: 'API & Development 4 docs' }).click();
  await page.getByRole('link', { name: 'Category Box SC' }).click();
  await page.getByRole('link', { name: 'Category Grid 2 SC' }).click();
  await page.getByRole('link', { name: 'Category List SC' }).click();
  await page.getByRole('link', { name: 'Category Grid SC' }).click();
  await page.getByRole('link', { name: 'FAQ List Classic SC' }).click();
  await page.getByRole('link', { name: 'FAQ List Modern SC' }).click();
  await page.getByRole('heading', { name: 'Frequently Asked Questions' }).click();
  await page.getByRole('heading', { name: 'Shipping & Delivery' }).click();
  await page.locator('.betterdocs-faq-post').first().click();
  await page.getByText('We usually take 3-5 business').first().click();
  await page.getByRole('link', { name: 'Feedback Form SC' }).click();
  await page.getByLabel('Name: *').click();
  await page.getByLabel('Name: *').fill('Holand');
  await page.getByLabel('Email: *').click();
  await page.getByLabel('Email: *').fill('hi@gmsail.com');
  await page.getByLabel('Message: *').click();
  await page.getByLabel('Message: *').fill('kmn acjo?');
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByLabel('Name: *').click();
  await page.getByLabel('Name: *').fill('hi');
  await page.getByLabel('Email: *').click();
  await page.getByLabel('Email: *').fill('hello@gmail.com');
  await page.getByLabel('Message: *').click();
  await page.getByLabel('Message: *').fill('hi hello');
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByText('Message was not sent. Try').click();
  await page.getByRole('link', { name: 'MK List SC' }).click();
  await page.getByRole('heading', { name: 'MK List SC' }).click();
  await page.getByText('No posts found!').click();
  await page.getByRole('link', { name: 'Multiple KB 2 SC' }).click();
  await page.getByRole('heading', { name: 'Multiple KB 2 SC' }).click();
  await page.locator('#post-270 div').nth(2).click();
  await page.getByRole('link', { name: 'KB Tab Grid SC' }).click();
  await page.locator('#post-272').click();
  await page.getByRole('link', { name: 'Multiple KB SC' }).click();
  await page.getByRole('heading', { name: 'Multiple KB SC' }).click();
  await page.locator('#post-269 div').nth(2).click();
  await page.getByRole('link', { name: 'Popular Articles SC' }).click();
  await page.getByRole('heading', { name: 'Popular Articles SC' }).click();
  await page.getByRole('heading', { name: 'Popular Docs' }).click();
  await page.locator('li').filter({ hasText: 'Mercedes GLS450: Here’s why' }).click();
  await page.getByRole('link', { name: 'Search Form SC' }).click();
  await page.locator('form').click();
  await page.getByPlaceholder('Search').fill('mercedes');
  await page.getByRole('link', { name: 'Mercedes GLS450: Here’s why' }).click();
  await page.locator('#betterdocs-breadcrumb').getByText('Mercedes GLS450: Here’s why').click();
  await page.getByText('Table of Contents This is').click();
  await page.getByRole('link', { name: 'This is first title' }).click();
  await page.getByRole('link', { name: 'This is first title' }).click();
  await page.getByText('This is first titleThis is').click();
  await page.getByRole('link', { name: 'This is 2nd title' }).click();
  await page.locator('.simplebar-content > div:nth-child(2)').click();
  await page.locator('.simplebar-content > div:nth-child(2)').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Facebook' }).click();
  const page1 = await page1Promise;
  await page.getByRole('link', { name: 'This is first title' }).click();
  await page.getByRole('link', { name: 'This is 2nd title' }).click();
  await page.locator('li').filter({ hasText: 'Happy' }).click();
  await page.getByText('This surge in exotic sales').click();
  await page.getByText('Updated on September 25,').nth(2).click();
  await page.getByText('Attachments').click();
  await page.locator('div').filter({ hasText: /^sunset507 KB$/ }).nth(1).click();
  await page.locator('#betterdocs-single-main').getByText('Related Docs').click();
  await page.getByRole('link', { name: 'Does your solution provide an' }).click();
});